baseURL = "https://noobcode.info"
title = "N00bCode.info"
languageCode = "en"
DefaultContentLanguage = "en"
theme = "hugo.386"
preserveTaxonomyNames = true

[params]
    # The name to display as main title in the home page
    mainpagetitle = "N00bCode.info - v.0.1.3"

    # The subtitle to display under the title in the home page
    mainpagesubtitle = "Hello stranger! Welcome to my personal site." 

    # The name to display as main title in the home page
    mainpagedesc = "N00bCode.info is my personal site."

    # The name to display in the copyright section in the footer
    copyrightname = "baduker"

    # The url to use as link in the copyright name in the footer. Leave empty to use none.
    copyrighturl = "https://github.com/baduker"

    # Show the "built on Hugo" disclaimer
    showhugo = true

    # Show the "hosted on" disclaimer
    hosted=true

    # Urls for social networks
    linkedin = "https://www.linkedin.com/in/maciekt/"
    github = "https://github.com/baduker"

    # Enables or disables the loading animations. false activates them. Default is false.
    loadfastload = false

    # Sets the speed for the page loading effect. Default is 1.0.
    loadspeedfactor = 1.5

    # Enables or disables the second flyby cursor. Default is false.
    loadonepass = true

[menu]
  [[menu.main]]
    identifier = "baduker"
    name = "Who Am I?"
    url = "/whoami/"
    weight = 10


  [[menu.main]]
    identifier = "posts"
    name = "All posts"
    url = "/post/"
    weight = 20

  [[menu.main]]
    identifier = "about"
    name = "About Hugo"
    url = "/about/"
    weight = 30

[taxonomies]
category = "categories"
tag = "tags"


[privacy]

  [privacy.vimeo]
    disabled = false
    simple = true

  [privacy.twitter]
    disabled = false
    enableDNT = true
    simple = true

  [privacy.instagram]
    disabled = false
    simple = true

  [privacy.youtube]
    disabled = false
    privacyEnhanced = true

[services]

  [services.instagram]
    disableInlineCSS = true

  [services.twitter]
    disableInlineCSS = true
